### ISSUE TITLE
Crash when closing inventory

### ISSUE THREAD

**Issue by zabi94** [maruohon/itemscroller#10] opened 2017-07-30 08:51 UTC
Crash in version 1.12.0-0.11.0

Closing inventory with my e button crashes my client when connected to a remote server.

here's the [crashlog](https://pastebin.com/mKuhdeUB)
here's the [modlist](https://pastebin.com/vrAJiqbG)

**Comment by maruohon** [comment] 2017-07-30 09:10
Hmm, have you unbound the recipe key? Does this happen every time?

**Comment by maruohon** [comment] 2017-07-31 10:46
Could you check what your Recipe keybinding for Item Scroller is set to, please? I couldn't reproduce this crash (in SP) when I unbound it (ie. hit esc to set it to `None`). In your case it's somehow crashing via the LWJGL library, while checking if the recipe keybinding is currently being pressed.

**Comment by maruohon** [comment] 2018-07-10 14:36
This should be fixed in 0.12.0.

**Closed by maruohon** 2018-07-10 14:36 UTC
